#!/bin/bash
echo "                                              "
echo "                    ****                      "
echo "                    *******                   "
echo "                    **********                "
echo "                    ****   ******             "
echo "                    ****      *****           "
echo "           ******   ****   ******             "
echo "              ****************                "
echo "                  ********                    "
echo "              ****************                "
echo "           ******   ****   ******             "
echo "                    ****      *****           "
echo "                    ****   ******             "
echo "                    **********                "
echo "                    *******                   "
echo "                    ****                      "
echo "                                              "
echo "                                              "
echo "        Võimas-Bluetooth-Taasühendaja         "
echo "                                              "
echo ""
read -n 1 -s -r -p "Vajuta suvalist klahvi alustamiseks."
echo ""
blutoothd -ls| grep "jcb"
echo ""
read -n 1 -s -r -p "Vajuta suvalist klahvi lõpetamiseks."
